name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Set up Docker Buildx (for better caching and multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build and push the image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-gpu-app:latest

      # 5. (Optional) Show image digest
      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}
